//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentExtensionsGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

namespace Entitas {

    public partial class Entity {

        public ActionInputComponent actionInput { get { return (ActionInputComponent)GetComponent(InputComponentIds.ActionInput); } }
        public bool hasActionInput { get { return HasComponent(InputComponentIds.ActionInput); } }

        public Entity AddActionInput(PlayerActionType newValue) {
            var component = CreateComponent<ActionInputComponent>(InputComponentIds.ActionInput);
            component.value = newValue;
            return AddComponent(InputComponentIds.ActionInput, component);
        }

        public Entity ReplaceActionInput(PlayerActionType newValue) {
            var component = CreateComponent<ActionInputComponent>(InputComponentIds.ActionInput);
            component.value = newValue;
            ReplaceComponent(InputComponentIds.ActionInput, component);
            return this;
        }

        public Entity RemoveActionInput() {
            return RemoveComponent(InputComponentIds.ActionInput);
        }
    }
}

    public partial class InputMatcher {

        static IMatcher _matcherActionInput;

        public static IMatcher ActionInput {
            get {
                if(_matcherActionInput == null) {
                    var matcher = (Matcher)Matcher.AllOf(InputComponentIds.ActionInput);
                    matcher.componentNames = InputComponentIds.componentNames;
                    _matcherActionInput = matcher;
                }

                return _matcherActionInput;
            }
        }
    }
