//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentExtensionsGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Entitas {

    public partial class Entity {

        public ActionInputComponent actionInput { get { return (ActionInputComponent)GetComponent(ComponentIds.ActionInput); } }
        public bool hasActionInput { get { return HasComponent(ComponentIds.ActionInput); } }

        public Entity AddActionInput(PlayerActionType newAction) {
            var component = CreateComponent<ActionInputComponent>(ComponentIds.ActionInput);
            component.action = newAction;
            return AddComponent(ComponentIds.ActionInput, component);
        }

        public Entity ReplaceActionInput(PlayerActionType newAction) {
            var component = CreateComponent<ActionInputComponent>(ComponentIds.ActionInput);
            component.action = newAction;
            ReplaceComponent(ComponentIds.ActionInput, component);
            return this;
        }

        public Entity RemoveActionInput() {
            return RemoveComponent(ComponentIds.ActionInput);
        }
    }

    public partial class Matcher {

        static IMatcher _matcherActionInput;

        public static IMatcher ActionInput {
            get {
                if(_matcherActionInput == null) {
                    var matcher = (Matcher)Matcher.AllOf(ComponentIds.ActionInput);
                    matcher.componentNames = ComponentIds.componentNames;
                    _matcherActionInput = matcher;
                }

                return _matcherActionInput;
            }
        }
    }
}
