//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentExtensionsGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

namespace Entitas {

    public partial class Entity {

        public AimInputComponent aimInput { get { return (AimInputComponent)GetComponent(InputComponentIds.AimInput); } }
        public bool hasAimInput { get { return HasComponent(InputComponentIds.AimInput); } }

        public Entity AddAimInput(UnityEngine.Vector2 newValue) {
            var component = CreateComponent<AimInputComponent>(InputComponentIds.AimInput);
            component.value = newValue;
            return AddComponent(InputComponentIds.AimInput, component);
        }

        public Entity ReplaceAimInput(UnityEngine.Vector2 newValue) {
            var component = CreateComponent<AimInputComponent>(InputComponentIds.AimInput);
            component.value = newValue;
            ReplaceComponent(InputComponentIds.AimInput, component);
            return this;
        }

        public Entity RemoveAimInput() {
            return RemoveComponent(InputComponentIds.AimInput);
        }
    }
}

    public partial class InputMatcher {

        static IMatcher _matcherAimInput;

        public static IMatcher AimInput {
            get {
                if(_matcherAimInput == null) {
                    var matcher = (Matcher)Matcher.AllOf(InputComponentIds.AimInput);
                    matcher.componentNames = InputComponentIds.componentNames;
                    _matcherAimInput = matcher;
                }

                return _matcherAimInput;
            }
        }
    }
