//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentExtensionsGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Entitas {

    public partial class Entity {

        public CageComponent cage { get { return (CageComponent)GetComponent(ComponentIds.Cage); } }
        public bool hasCage { get { return HasComponent(ComponentIds.Cage); } }

        public Entity AddCage(PlayerIndex newPlayerIndex, UnityEngine.GameObject newGameObject) {
            var component = CreateComponent<CageComponent>(ComponentIds.Cage);
            component.playerIndex = newPlayerIndex;
            component.gameObject = newGameObject;
            return AddComponent(ComponentIds.Cage, component);
        }

        public Entity ReplaceCage(PlayerIndex newPlayerIndex, UnityEngine.GameObject newGameObject) {
            var component = CreateComponent<CageComponent>(ComponentIds.Cage);
            component.playerIndex = newPlayerIndex;
            component.gameObject = newGameObject;
            ReplaceComponent(ComponentIds.Cage, component);
            return this;
        }

        public Entity RemoveCage() {
            return RemoveComponent(ComponentIds.Cage);
        }
    }

    public partial class Matcher {

        static IMatcher _matcherCage;

        public static IMatcher Cage {
            get {
                if(_matcherCage == null) {
                    var matcher = (Matcher)Matcher.AllOf(ComponentIds.Cage);
                    matcher.componentNames = ComponentIds.componentNames;
                    _matcherCage = matcher;
                }

                return _matcherCage;
            }
        }
    }
}
