//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentIndicesGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class ComponentIds {

    public const int ActionInput = 0;
    public const int AimInput = 1;
    public const int Cage = 2;
    public const int MovementInput = 3;
    public const int Player = 4;

    public const int TotalComponents = 5;

    public static readonly string[] componentNames = {
        "ActionInput",
        "AimInput",
        "Cage",
        "MovementInput",
        "Player"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(ActionInputComponent),
        typeof(AimInputComponent),
        typeof(CageComponent),
        typeof(MovementInputComponent),
        typeof(PlayerComponent)
    };
}
