//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentIndicesGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class InputComponentIds {

    public const int PlayerIndex = 0;
    public const int ActionInput = 1;
    public const int AimInput = 2;
    public const int MovementInput = 3;

    public const int TotalComponents = 4;

    public static readonly string[] componentNames = {
        "PlayerIndex",
        "ActionInput",
        "AimInput",
        "MovementInput"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(PlayerIndexComponent),
        typeof(ActionInputComponent),
        typeof(AimInputComponent),
        typeof(MovementInputComponent)
    };
}
