//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentExtensionsGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

namespace Entitas {

    public partial class Entity {

        public MovementInputComponent movementInput { get { return (MovementInputComponent)GetComponent(InputComponentIds.MovementInput); } }
        public bool hasMovementInput { get { return HasComponent(InputComponentIds.MovementInput); } }

        public Entity AddMovementInput(float newValue) {
            var component = CreateComponent<MovementInputComponent>(InputComponentIds.MovementInput);
            component.value = newValue;
            return AddComponent(InputComponentIds.MovementInput, component);
        }

        public Entity ReplaceMovementInput(float newValue) {
            var component = CreateComponent<MovementInputComponent>(InputComponentIds.MovementInput);
            component.value = newValue;
            ReplaceComponent(InputComponentIds.MovementInput, component);
            return this;
        }

        public Entity RemoveMovementInput() {
            return RemoveComponent(InputComponentIds.MovementInput);
        }
    }
}

    public partial class InputMatcher {

        static IMatcher _matcherMovementInput;

        public static IMatcher MovementInput {
            get {
                if(_matcherMovementInput == null) {
                    var matcher = (Matcher)Matcher.AllOf(InputComponentIds.MovementInput);
                    matcher.componentNames = InputComponentIds.componentNames;
                    _matcherMovementInput = matcher;
                }

                return _matcherMovementInput;
            }
        }
    }
