//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentExtensionsGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Entitas {

    public partial class Entity {

        public MovementInputComponent movementInput { get { return (MovementInputComponent)GetComponent(ComponentIds.MovementInput); } }
        public bool hasMovementInput { get { return HasComponent(ComponentIds.MovementInput); } }

        public Entity AddMovementInput(PlayerIndex newPlayerIndex, float newValue) {
            var component = CreateComponent<MovementInputComponent>(ComponentIds.MovementInput);
            component.playerIndex = newPlayerIndex;
            component.value = newValue;
            return AddComponent(ComponentIds.MovementInput, component);
        }

        public Entity ReplaceMovementInput(PlayerIndex newPlayerIndex, float newValue) {
            var component = CreateComponent<MovementInputComponent>(ComponentIds.MovementInput);
            component.playerIndex = newPlayerIndex;
            component.value = newValue;
            ReplaceComponent(ComponentIds.MovementInput, component);
            return this;
        }

        public Entity RemoveMovementInput() {
            return RemoveComponent(ComponentIds.MovementInput);
        }
    }

    public partial class Matcher {

        static IMatcher _matcherMovementInput;

        public static IMatcher MovementInput {
            get {
                if(_matcherMovementInput == null) {
                    var matcher = (Matcher)Matcher.AllOf(ComponentIds.MovementInput);
                    matcher.componentNames = ComponentIds.componentNames;
                    _matcherMovementInput = matcher;
                }

                return _matcherMovementInput;
            }
        }
    }
}
