//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentIndicesGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class ObjectsComponentIds {

    public const int PlayerIndex = 0;
    public const int Cage = 1;
    public const int PlayerActions = 2;
    public const int View = 3;

    public const int TotalComponents = 4;

    public static readonly string[] componentNames = {
        "PlayerIndex",
        "Cage",
        "PlayerActions",
        "View"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(PlayerIndexComponent),
        typeof(CageComponent),
        typeof(PlayerActionsComponent),
        typeof(ViewComponent)
    };
}
