//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.ComponentExtensionsGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Entitas;

namespace Entitas {

    public partial class Entity {

        public PlayerActionsComponent playerActions { get { return (PlayerActionsComponent)GetComponent(ObjectsComponentIds.PlayerActions); } }
        public bool hasPlayerActions { get { return HasComponent(ObjectsComponentIds.PlayerActions); } }

        public Entity AddPlayerActions(PlayerActions newValue) {
            var component = CreateComponent<PlayerActionsComponent>(ObjectsComponentIds.PlayerActions);
            component.value = newValue;
            return AddComponent(ObjectsComponentIds.PlayerActions, component);
        }

        public Entity ReplacePlayerActions(PlayerActions newValue) {
            var component = CreateComponent<PlayerActionsComponent>(ObjectsComponentIds.PlayerActions);
            component.value = newValue;
            ReplaceComponent(ObjectsComponentIds.PlayerActions, component);
            return this;
        }

        public Entity RemovePlayerActions() {
            return RemoveComponent(ObjectsComponentIds.PlayerActions);
        }
    }
}

    public partial class ObjectsMatcher {

        static IMatcher _matcherPlayerActions;

        public static IMatcher PlayerActions {
            get {
                if(_matcherPlayerActions == null) {
                    var matcher = (Matcher)Matcher.AllOf(ObjectsComponentIds.PlayerActions);
                    matcher.componentNames = ObjectsComponentIds.componentNames;
                    _matcherPlayerActions = matcher;
                }

                return _matcherPlayerActions;
            }
        }
    }
