//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGenerator.PoolsGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Entitas {

    public partial class Pools {

        public static Pool CreateInputPool() {
            return CreatePool("Input", InputComponentIds.TotalComponents, InputComponentIds.componentNames, InputComponentIds.componentTypes);
        }

        public static Pool CreateObjectsPool() {
            return CreatePool("Objects", ObjectsComponentIds.TotalComponents, ObjectsComponentIds.componentNames, ObjectsComponentIds.componentTypes);
        }

        public static Pool CreateSettingsPool() {
            return CreatePool("Settings", SettingsComponentIds.TotalComponents, SettingsComponentIds.componentNames, SettingsComponentIds.componentTypes);
        }

        public Pool[] allPools { get { return new [] { input, objects, settings }; } }

        public Pool input;
        public Pool objects;
        public Pool settings;

        public void SetAllPools() {
            input = CreateInputPool();
            objects = CreateObjectsPool();
            settings = CreateSettingsPool();
        }
    }
}
